apiVersion: v1
kind: Pod
metadata:
 name: datanodep3
 labels:
  zone: prod
  version: v1
  component: datanode
spec:
 containers:
 - name: datanode
   image: mallanpatil/hadoop:2.7.3
   ports:
   - containerPort: 50010
   - containerPort: 50020
   - containerPort: 50070

   command: ["/bin/sh","./startDatanode.sh"] 
     
   volumeMounts: 
   - name: data-dir
     mountPath: /opt/hadoop/data/dfs/data
   - name: data-conf
     mountPath: /opt/hadoop/data/conf
   - name: data-log
     mountPath: /opt/hadoop/data/logs
   resources:
     requests:
       memory: "5Gi"
     limits:
       memory: "5Gi" 
 volumes: 
   - name: data-dir
     hostPath: 
       path: /loddisk2/data/dn-store
       type: Directory
   - name: data-conf
     hostPath:
       path: /loddisk2/data/conf
   - name: data-log
     hostPath:
       path: /loddisk2/data/logs
 nodeSelector:
   node: datanode

