apiVersion: v1
kind: Service
metadata:
 name: namenode
 labels:
  zone: prod
  version: v1
  component: namenode
spec:
 type: NodePort
 ports:
 - port: 9000
   targetPort: 9000
   nodePort: 30005
   name: rpc
 - port: 9870
   targetPort: 50070
   nodePort: 30006
   name: web
 selector:
  zone: prod
  version: v1
  component: namenode
